'use client';

import React, { useState, useEffect } from 'react';
import { Modal } from '@/components/ui/Modal';
import { Button } from '@/components/ui/Button';
import { FileUpload, UploadedFile } from '@/components/ui/FileUpload';
import { Loader } from '@/components/ui/Loader';
import { Send, Edit3, ShieldAlert } from 'lucide-react';
import apiClient from '@/lib/axios';

interface RequestComposerModalProps {
  isOpen: boolean;
  onClose: () => void;
  caseId: string;
  stepId: string;
  departmentEntityId: string;
  onSuccess: () => void;
}

export function RequestComposerModal({ isOpen, onClose, caseId, stepId, departmentEntityId, onSuccess }: RequestComposerModalProps) {
  const [loading, setLoading] = useState(false);
  const [actionLoading, setActionLoading] = useState(false);
  const [draft, setDraft] = useState<any>(null);
  const [editableContent, setEditableContent] = useState('');
  const [evidence, setEvidence] = useState<UploadedFile[]>([]);
  
  // Fetch or create draft on open
  useEffect(() => {
    if (isOpen && caseId && stepId && departmentEntityId) {
      const initDraft = async () => {
        setLoading(true);
        try {
          // Check if we already have a draft for this step. If not, generate one.
          // This requires a POST to /draft
          const res = await apiClient.post(`/cases/${caseId}/requests/draft`, {
            step_id: stepId,
            department_entity_id: departmentEntityId,
            request_type: 'information',
            recipient_type: 'department'
          });
          const newDraft = res.data.data;
          setDraft(newDraft);
          setEditableContent(newDraft.draft_content || '');
        } catch (error) {
          console.error("Failed to generate draft", error);
        } finally {
          setLoading(false);
        }
      };
      initDraft();
    }
  }, [isOpen, caseId, stepId, departmentEntityId]);

  const handleUpdateDraft = async () => {
    if (!draft) return;
    setActionLoading(true);
    try {
      await apiClient.patch(`/cases/${caseId}/requests/${draft.request_id}`, {
        draft_content: editableContent
      });
      // Optionally show toast
    } catch (error) {
      console.error("Update failed", error);
    } finally {
      setActionLoading(false);
    }
  };

  const handleSend = async () => {
    if (!draft) return;
    setActionLoading(true);
    try {
      // If content changed, save first
      if (editableContent !== draft.draft_content) {
        await apiClient.patch(`/cases/${caseId}/requests/${draft.request_id}`, {
          draft_content: editableContent
        });
      }

      // If we uploaded evidence, we need to attach it to the complaint or request first.
      // For simplicity in Phase 12, we assume they are attached to the case evidence via another endpoint or the composer natively handles it if we send it in payload.
      // But the endpoint `POST /:id/requests/:reqId/send` takes no body.
      // So we just send it.
      await apiClient.post(`/cases/${caseId}/requests/${draft.request_id}/send`);
      onSuccess();
    } catch (error) {
      console.error("Send failed", error);
    } finally {
      setActionLoading(false);
    }
  };

  if (!isOpen) return null;

  return (
    <Modal
      isOpen={isOpen}
      onClose={onClose}
      title={`Request Composer: ${departmentEntityId}`}
      size="lg"
      footer={
        <div className="flex gap-3 justify-end w-full">
          <Button variant="ghost" onClick={onClose} disabled={actionLoading}>Cancel</Button>
          <Button variant="secondary" onClick={handleUpdateDraft} isLoading={actionLoading} leftIcon={<Edit3 size={15}/>}>
            Save Draft
          </Button>
          <Button onClick={handleSend} isLoading={actionLoading} leftIcon={<Send size={15}/>}>
            Send Official Request
          </Button>
        </div>
      }
    >
      {loading ? (
        <div className="py-12 flex justify-center"><Loader /></div>
      ) : draft ? (
        <div className="space-y-6">
          <div className="bg-yellow-50 border border-yellow-200 p-3 rounded-lg flex gap-3 text-sm text-yellow-800">
            <ShieldAlert className="flex-shrink-0 mt-0.5" size={18} />
            <p>
              This draft was automatically generated by AI based on the current case facts and checklist requirements. 
              Please review and edit before officially dispatching to the <strong>{departmentEntityId}</strong> department.
            </p>
          </div>

          <div className="bg-white border border-neutral-200 rounded-lg p-3 text-sm flex flex-col gap-1 shadow-sm">
            <div className="flex">
              <span className="text-neutral-500 font-medium w-16">To:</span>
              <span className="font-semibold text-neutral-800">{departmentEntityId.toLowerCase().replace(/[^a-z0-9_]/g, '_')}@leo.mockdept.local</span>
            </div>
            <div className="flex">
              <span className="text-neutral-500 font-medium w-16">Subject:</span>
              <span className="font-semibold text-neutral-800">Official Request [Ref: {draft.request_id.substring(0, 8)}]</span>
            </div>
          </div>

          <div>
            <label className="block text-xs font-bold text-neutral-500 uppercase tracking-wider mb-2">Draft Content</label>
            <textarea 
              value={editableContent}
              onChange={(e) => setEditableContent(e.target.value)}
              rows={12}
              className="w-full p-4 font-mono text-sm border border-neutral-300 rounded-lg focus:ring-2 focus:ring-primary-500 focus:outline-none bg-neutral-50"
            />
          </div>

          <div>
            <label className="block text-xs font-bold text-neutral-500 uppercase tracking-wider mb-2">Attach Supporting Evidence (Optional)</label>
            <FileUpload 
              value={evidence}
              onChange={setEvidence}
              maxFiles={3}
            />
          </div>
        </div>
      ) : (
        <div className="py-12 text-center text-red-500">Failed to load draft</div>
      )}
    </Modal>
  );
}
